import { ClientTypes } from '../../../common/utils/rfvClassification';

// Cobre todas as 125 combinações possíveis (R1-5 × F1-5 × M1-5)
export const RFV_SEGMENTATION_MATRIX: Record<string, string> = {

    // ─── R=5 (muito recente) ───────────────────────────────────────────────────
    '555': ClientTypes.Campeao,
    '554': ClientTypes.Campeao,
    '553': ClientTypes.Fiel,
    '552': ClientTypes.EmPotencial,
    '551': ClientTypes.Novo,
    '545': ClientTypes.Campeao,
    '544': ClientTypes.Fiel,
    '543': ClientTypes.Fiel,
    '542': ClientTypes.EmPotencial,
    '541': ClientTypes.Novo,
    '535': ClientTypes.EmPotencial,
    '534': ClientTypes.EmPotencial,
    '533': ClientTypes.EmPotencial,
    '532': ClientTypes.Promissor,
    '531': ClientTypes.Promissor,
    '525': ClientTypes.Novo,
    '524': ClientTypes.Novo,
    '523': ClientTypes.Novo,
    '522': ClientTypes.Novo,
    '521': ClientTypes.Novo,
    '515': ClientTypes.Novo,
    '514': ClientTypes.Novo,
    '513': ClientTypes.Novo,
    '512': ClientTypes.Novo,
    '511': ClientTypes.Novo,

    // ─── R=4 (recente) ────────────────────────────────────────────────────────
    '455': ClientTypes.Campeao,
    '454': ClientTypes.Fiel,
    '453': ClientTypes.Fiel,
    '452': ClientTypes.EmPotencial,
    '451': ClientTypes.EmPotencial,
    '445': ClientTypes.Fiel,
    '444': ClientTypes.Fiel,
    '443': ClientTypes.Fiel,
    '442': ClientTypes.EmPotencial,
    '441': ClientTypes.EmPotencial,
    '435': ClientTypes.EmPotencial,
    '434': ClientTypes.EmPotencial,
    '433': ClientTypes.EmPotencial,
    '432': ClientTypes.PrecisaDeAtencao,
    '431': ClientTypes.PrecisaDeAtencao,
    '425': ClientTypes.Promissor,
    '424': ClientTypes.Promissor,
    '423': ClientTypes.Promissor,
    '422': ClientTypes.PrecisaDeAtencao,
    '421': ClientTypes.PrecisaDeAtencao,
    '415': ClientTypes.Promissor,
    '414': ClientTypes.Promissor,
    '413': ClientTypes.Promissor,
    '412': ClientTypes.PrecisaDeAtencao,
    '411': ClientTypes.PrecisaDeAtencao,

    // ─── R=3 (recência média) ──────────────────────────────────────────────────
    '355': ClientTypes.Fiel,
    '354': ClientTypes.Fiel,
    '353': ClientTypes.Fiel,
    '352': ClientTypes.EmPotencial,
    '351': ClientTypes.PrecisaDeAtencao,
    '345': ClientTypes.EmPotencial,
    '344': ClientTypes.EmPotencial,
    '343': ClientTypes.EmPotencial,
    '342': ClientTypes.PrecisaDeAtencao,
    '341': ClientTypes.PrecisaDeAtencao,
    '335': ClientTypes.PrecisaDeAtencao,
    '334': ClientTypes.PrecisaDeAtencao,
    '333': ClientTypes.PrecisaDeAtencao,
    '332': ClientTypes.PrecisaDeAtencao,
    '331': ClientTypes.QuaseDormente,
    '325': ClientTypes.PrecisaDeAtencao,
    '324': ClientTypes.PrecisaDeAtencao,
    '323': ClientTypes.PrecisaDeAtencao,
    '322': ClientTypes.QuaseDormente,
    '321': ClientTypes.QuaseDormente,
    '315': ClientTypes.PrecisaDeAtencao,
    '314': ClientTypes.PrecisaDeAtencao,
    '313': ClientTypes.QuaseDormente,
    '312': ClientTypes.QuaseDormente,
    '311': ClientTypes.QuaseDormente,

    // ─── R=2 (baixa recência) ──────────────────────────────────────────────────
    '255': ClientTypes.NaoPossoPerder,
    '254': ClientTypes.NaoPossoPerder,
    '253': ClientTypes.EmRisco,
    '252': ClientTypes.EmRisco,
    '251': ClientTypes.EmRisco,
    '245': ClientTypes.NaoPossoPerder,
    '244': ClientTypes.EmRisco,
    '243': ClientTypes.EmRisco,
    '242': ClientTypes.EmRisco,
    '241': ClientTypes.EmRisco,
    '235': ClientTypes.EmRisco,
    '234': ClientTypes.EmRisco,
    '233': ClientTypes.EmRisco,
    '232': ClientTypes.QuaseDormente,
    '231': ClientTypes.QuaseDormente,
    '225': ClientTypes.QuaseDormente,
    '224': ClientTypes.QuaseDormente,
    '223': ClientTypes.QuaseDormente,
    '222': ClientTypes.Hibernando,
    '221': ClientTypes.Hibernando,
    '215': ClientTypes.QuaseDormente,
    '214': ClientTypes.QuaseDormente,
    '213': ClientTypes.Hibernando,
    '212': ClientTypes.Hibernando,
    '211': ClientTypes.Hibernando,

    // ─── R=1 (inativo) ────────────────────────────────────────────────────────
    '155': ClientTypes.NaoPossoPerder,
    '154': ClientTypes.NaoPossoPerder,
    '153': ClientTypes.EmRisco,
    '152': ClientTypes.EmRisco,
    '151': ClientTypes.EmRisco,
    '145': ClientTypes.NaoPossoPerder,
    '144': ClientTypes.EmRisco,
    '143': ClientTypes.EmRisco,
    '142': ClientTypes.EmRisco,
    '141': ClientTypes.Hibernando,
    '135': ClientTypes.EmRisco,
    '134': ClientTypes.EmRisco,
    '133': ClientTypes.Hibernando,
    '132': ClientTypes.Hibernando,
    '131': ClientTypes.Hibernando,
    '125': ClientTypes.Hibernando,
    '124': ClientTypes.Hibernando,
    '123': ClientTypes.Hibernando,
    '122': ClientTypes.Perdido,
    '121': ClientTypes.Perdido,
    '115': ClientTypes.Hibernando,
    '114': ClientTypes.Perdido,
    '113': ClientTypes.Perdido,
    '112': ClientTypes.Perdido,
    '111': ClientTypes.Perdido,
};

export function getSegmentFromRfvKey(rfvKey: string): string {
    return RFV_SEGMENTATION_MATRIX[rfvKey] ?? ClientTypes.Novo;
}
