import { WeatherData } from '../../../domain/weather-data.entity';

export class WeatherDataMapper {
    static toDomain(prismaWeatherData: any): WeatherData {
        return new WeatherData({
            id: prismaWeatherData.id,
            cityName: prismaWeatherData.cityName,
            region: prismaWeatherData.region,
            country: prismaWeatherData.country,
            lat: prismaWeatherData.lat,
            lon: prismaWeatherData.lon,
            tzId: prismaWeatherData.tzId,
            localtimeEpoch: prismaWeatherData.localtimeEpoch ? Number(prismaWeatherData.localtimeEpoch) : 0,
            localtime: prismaWeatherData.localtime,
            lastUpdatedEpoch: prismaWeatherData.lastUpdatedEpoch ? Number(prismaWeatherData.lastUpdatedEpoch) : 0,
            lastUpdated: prismaWeatherData.lastUpdated,
            tempC: prismaWeatherData.tempC,
            tempF: prismaWeatherData.tempF,
            isDay: prismaWeatherData.isDay,
            conditionText: prismaWeatherData.conditionText,
            conditionIcon: prismaWeatherData.conditionIcon,
            conditionCode: prismaWeatherData.conditionCode,
            windMph: prismaWeatherData.windMph,
            windKph: prismaWeatherData.windKph,
            windDegree: prismaWeatherData.windDegree,
            windDir: prismaWeatherData.windDir,
            pressureMb: prismaWeatherData.pressureMb,
            pressureIn: prismaWeatherData.pressureIn,
            precipMm: prismaWeatherData.precipMm,
            precipIn: prismaWeatherData.precipIn,
            humidity: prismaWeatherData.humidity,
            cloud: prismaWeatherData.cloud,
            feelslikeC: prismaWeatherData.feelslikeC,
            feelslikeF: prismaWeatherData.feelslikeF,
            windchillC: prismaWeatherData.windchillC,
            windchillF: prismaWeatherData.windchillF,
            heatindexC: prismaWeatherData.heatindexC,
            heatindexF: prismaWeatherData.heatindexF,
            dewpointC: prismaWeatherData.dewpointC,
            dewpointF: prismaWeatherData.dewpointF,
            visKm: prismaWeatherData.visKm,
            visMiles: prismaWeatherData.visMiles,
            uv: prismaWeatherData.uv,
            gustMph: prismaWeatherData.gustMph,
            gustKph: prismaWeatherData.gustKph,
            shortRad: prismaWeatherData.shortRad,
            diffRad: prismaWeatherData.diffRad,
            dni: prismaWeatherData.dni,
            gti: prismaWeatherData.gti,
            createdAt: prismaWeatherData.createdAt,
            updatedAt: prismaWeatherData.updatedAt,
        });
    }
}
