-- AlterEnum
ALTER TYPE "AdminRole" ADD VALUE IF NOT EXISTS 'SDR';
ALTER TYPE "AdminRole" ADD VALUE IF NOT EXISTS 'CLOSER';
ALTER TYPE "AdminRole" ADD VALUE IF NOT EXISTS 'REVOPS';
ALTER TYPE "AdminRole" ADD VALUE IF NOT EXISTS 'CSM';
ALTER TYPE "AdminRole" ADD VALUE IF NOT EXISTS 'CS';
