import type { RfvSegmentPosition } from '@/types'

export const RFV_SEGMENT_POSITIONS: RfvSegmentPosition[] = [
  {
    key: 'nao_posso_perder',
    label: 'Clientes que não posso perder',
    gridRow: 1,
    gridRowEnd: 2,
    gridColumn: 1,
  },
  {
    key: 'campeao',
    label: 'Campeões',
    gridRow: 1,
    gridColumn: 5,
    gridColumnEnd: 6,
  },
  {
    key: 'em_risco',
    label: 'Clientes em risco',
    gridRow: 1,
    gridRowEnd: 4,
    gridColumn: 1,
    gridColumnEnd: 3,
  },
  {
    key: 'precisa_de_atencao',
    label: 'Clientes que precisam de atenção',
    gridRow: 3,
    gridRowEnd: 4,
    gridColumn: 3,
  },
  {
    key: 'quase_dormente',
    label: 'Clientes quase dormentes',
    gridRow: 4,
    gridRowEnd: 6,
    gridColumn: 3,
    gridColumnEnd: 4,
  },
  {
    key: 'fiel',
    label: 'Clientes fiéis',
    gridRow: 1,
    gridRowEnd: 3,
    gridColumn: 3,
    gridColumnEnd: 6,
  },
  {
    key: 'em_potencial',
    label: 'Fiéis em potencial',
    gridRow: 3,
    gridRowEnd: 5,
    gridColumn: 4,
    gridColumnEnd: 6,
  },
  {
    key: 'novo',
    label: 'Novos clientes',
    gridRow: 5,
    gridColumn: 5,
    gridColumnEnd: 0,
    gridRowEnd: 6,
  },
  {
    key: 'hibernando',
    label: 'Clientes hibernando',
    gridRow: 4,
    gridColumn: 2,
  },
  {
    key: 'promissor',
    label: 'Clientes promissores',
    gridRow: 5,
    gridColumn: 4,
    gridColumnEnd: 5,
  },
  {
    key: 'perdido',
    label: 'Clientes perdidos',
    gridRow: 4,
    gridRowEnd: 6,
    gridColumn: 1,
    gridColumnEnd: 3,
  },
]
